% CIELM - Convex Incremental Extreme Learning Machine Class
%   Train and Predict a SLFN based on Convex Incremental Extreme Learning Machine
%
%   This code was implemented based on the following paper:
%
%   [1] Huang, G. Bin, & Chen, L. (2007). 
%       Convex incremental extreme learning machine. 
%       Neurocomputing, 70(16–18), 3056–3062. 
%       https://doi.org/10.1016/j.neucom.2007.02.009
%
%   Attributes:
%       Attributes between *.* must be informed.
%       CIELM objects must be created using name-value pair arguments (see the Usage Example).
%
%         *numberOfInputNeurons*:   Number of neurons in the input layer.
%                Accepted Values:   Any positive integer.
%
%          numberOfHiddenNeurons:   Maximum number of neurons in the hidden layer
%                Accepted Values:   Any positive integer (defaut = 1000).
%
%                   maximumError:   Maximum error (used as stopping criterion)
%                Accepted Values:   Any positive real number. (default = 1e-3)
%
%             activationFunction:   Activation funcion for hidden layer
%                Accepted Values:   Function handle (see [1]) or one of these strings:
%                                       'sig':     Sigmoid (default)
%                                       'sin':     Sine
%                                       'hardlim': Hard Limit
%                                       'tribas':  Triangular basis function
%                                       'radbas':  Radial basis function
%
%                           seed:   Seed to generate the pseudo-random values.
%                                   This attribute is for reproducible research.
%                Accepted Values:   RandStream object or a integer seed for RandStream.
%
%       Attributes generated by the code:
%
%                    inputWeight:   Weight matrix that connects the input
%                                   layer to the hidden layer
%
%            biasOfHiddenNeurons:   Bias of hidden units
%
%                   outputWeight:   Weight matrix that connects the hidden
%                                   layer to the output layer
%
%   Methods:
%
%          obj = CIELM(varargin):   Creates IELM objects. varargin should be in
%                                   pairs. Look attributes
%
%           obj = obj.train(X,Y):   Method for training. X is the input of size N x n,
%                                   where N is (# of samples) and n is the (# of features).
%                                   Y is the output of size N x m, where m is (# of multiple outputs)
%
%          Yhat = obj.predict(X):   Predicts the output for X.
%
%   Usage Example:
%
%       load iris_dataset.mat
%       X    = irisInputs';
%       Y    = irisTargets';
%       [~,Y] = max(Y,[],2);    % Only one dimensional targets are supported by this method
%       ifelm  = CIELM('numberOfInputNeurons', 4, 'numberOfHiddenNeurons',100);
%       ifelm  = ifelm.train(X, Y);
%       Yhat = ifelm.predict(X)
%
%   License:
%
%   Permission to use, copy, or modify this software and its documentation
%   for educational and research purposes only and without fee is here
%   granted, provided that this copyright notice and the original authors'
%   names appear on all copies and supporting documentation. This program
%   shall not be used, rewritten, or adapted as the basis of a commercial
%   software or hardware product without first obtaining permission of the
%   authors. The authors make no representations about the suitability of
%   this software for any purpose. It is provided "as is" without express
%   or implied warranty.
%
%       Federal University of Espirito Santo (UFES), Brazil
%       Computers and Neural Systems Lab. (LabCISNE)
%       Authors:    B. L. S. Silva, F. K. Inaba, D. L. Cosmo
%       email:      labcisne@gmail.com
%       website:    github.com/labcisne/ELMToolbox
%       date:       Feb/2018


classdef CIELM < ELM
    properties
        maximumError = 1e-3
    end
    properties (SetAccess = private, GetAccess = public)
        error
    end
    methods
        function self = CIELM(varargin)
            self = self@ELM(varargin{:});
        end
        
        function self = train(self, X, Y)
            if size(Y,2) ~= 1
                throw(MException('CIELM:outputSize','CIELM method only supports one dimensional outputs'));
            end
            auxTime = toc;
            N = 0;
            self.inputWeight = [];
            self.biasOfHiddenNeurons = [];
            self.error = Y;
            while N < self.numberOfHiddenNeurons && norm(self.error) > self.maximumError
                N = N+1;
                Wnew = rand(self.seed, self.numberOfInputNeurons, 1)*2-1;
                Bnew = rand(self.seed, 1, 1);
                tempH = X*Wnew + repmat(Bnew,size(X,1),1);
                H = self.activationFunction(tempH);
                clear tempH;
                aux = (self.error - (Y - H));
                betaN = (aux'*self.error)/(aux'*aux);
                
                self.outputWeight = (1-betaN).*self.outputWeight;
                self.inputWeight = [self.inputWeight, Wnew];
                self.biasOfHiddenNeurons = [self.biasOfHiddenNeurons, Bnew];
                self.outputWeight = [self.outputWeight; betaN];

                self.error = (1 - betaN)*self.error + betaN*(Y - H);
                
            end
            self.trainTime = toc - auxTime;
        end
        
    end
end
