% EEM-ELM - Enhanced Error Minimized Extreme Learning Machine Class
%   Train and Predict a SLFN based on Enhanced Error Minimized Extreme Learning Machine
%
%   This code was implemented based on the following paper:
%
%   [1] Lan, Y., Soh, Y. C., & Huang, G. (2010). 
%       Random Search Enhancement of Error Minimized Extreme Learning Machine. 
%       European Symposium on Artificial Neural Networks (ESANN) 2010, (April), 28–30.
%
%   Attributes:
%       Attributes between *.* must be informed.
%       EEMELM objects must be created using name-value pair arguments (see the Usage Example).
%
%         *numberOfInputNeurons*:   Number of neurons in the input layer.
%                Accepted Values:   Any positive integer.
%
%          numberOfHiddenNeurons:   Initial number of neurons in the hidden layer
%                                   After training, this attribute contains the number of 
%                                   neurons in the hidden layer.
%                Accepted Values:   Any positive integer (defaut = 1).
%
%       maxNumberOfHiddenNeurons:   Maximum number of neurons in the hidden layer
%                Accepted Values:   Any positive integer (defaut = 1000).
%
%                   maximumError:   Maximum error (used as stopping criterion)
%                Accepted Values:   Any positive real number. (default = 1e-3)
%           
%          numberOfNeuronsByStep:   Number of neurons generated in each iteration
%                                   (Only one is selected)
%                Accepted Values:   Any positive integer number. (default = 10)
%
%             activationFunction:   Activation funcion for hidden layer
%                Accepted Values:   Function handle (see [1]) or one of these strings:
%                                       'sig':     Sigmoid (default)
%                                       'sin':     Sine
%                                       'hardlim': Hard Limit
%                                       'tribas':  Triangular basis function
%                                       'radbas':  Radial basis function
%
%                           seed:   Seed to generate the pseudo-random values.
%                                   This attribute is for reproducible research.
%                Accepted Values:   RandStream object or a integer seed for RandStream.
%
%       Attributes generated by the code:
%
%                    inputWeight:   Weight matrix that connects the input
%                                   layer to the hidden layer
%
%            biasOfHiddenNeurons:   Bias of hidden units
%
%                   outputWeight:   Weight matrix that connects the hidden
%                                   layer to the output layer
%
%   Methods:
%
%         obj = EEMELM(varargin):   Creates IELM objects. varargin should be in
%                                   pairs. Look attributes
%
%           obj = obj.train(X,Y):   Method for training. X is the input of size N x n,
%                                   where N is (# of samples) and n is the (# of features).
%                                   Y is the output of size N x m, where m is (# of multiple outputs)
%
%          Yhat = obj.predict(X):   Predicts the output for X.
%
%   Usage Example:
%
%       load iris_dataset.mat
%       X    = irisInputs';
%       Y    = irisTargets';
%       eemelm  = EEMELM('numberOfInputNeurons', 4, 'maxNumberOfHiddenNeurons',100);
%       eemelm  = eemelm.train(X, Y);
%       Yhat = eemelm.predict(X)
%
%   License:
%
%   Permission to use, copy, or modify this software and its documentation
%   for educational and research purposes only and without fee is here
%   granted, provided that this copyright notice and the original authors'
%   names appear on all copies and supporting documentation. This program
%   shall not be used, rewritten, or adapted as the basis of a commercial
%   software or hardware product without first obtaining permission of the
%   authors. The authors make no representations about the suitability of
%   this software for any purpose. It is provided "as is" without express
%   or implied warranty.
%
%       Federal University of Espirito Santo (UFES), Brazil
%       Computers and Neural Systems Lab. (LabCISNE)
%       Authors:    B. L. S. Silva, F. K. Inaba, D. L. Cosmo
%       email:      labcisne@gmail.com
%       website:    github.com/labcisne/ELMToolbox
%       date:       Feb/2018


classdef EEMELM < ELM
    properties
        maxNumberOfHiddenNeurons  = 1000
        pseudoInv
        maxError = 1e-3
        numberOfNeuronsByStep = 10
    end
    properties (Access = private)
        H
    end
    
    methods
        function self = EEMELM(varargin)
            self = self@ELM('numberOfHiddenNeurons',1,varargin{:});
        end
        
        function pi = pseudoinverse(~,h)
            if size(h,1)>=size(h,2)
                pi = pinv(h' * h) * h';
            else
                pi = h' * pinv(h * h');
            end
        end
        
        function self = train(self, X, Y)
            
            auxTime = toc;
            %Train with initial number of hidden neurons 
            tempH = X*self.inputWeight + repmat(self.biasOfHiddenNeurons,size(X,1),1);
            self.H = self.activationFunction(tempH);
            
            self.pseudoInv = self.pseudoinverse(self.H);
            self.outputWeight = self.pseudoInv * Y;
            
            E = norm(self.H*self.outputWeight - Y,'fro');
            
            while (self.numberOfHiddenNeurons < self.maxNumberOfHiddenNeurons) && (E > self.maxError)
                
                self.numberOfHiddenNeurons = self.numberOfHiddenNeurons + 1;
                
                Wnew = cell(1,self.numberOfNeuronsByStep);
                Bnew = cell(1,self.numberOfNeuronsByStep);
                deltaH = cell(1,self.numberOfNeuronsByStep);
                pseudoInvs = cell(1,self.numberOfNeuronsByStep);
                
                for j=1:self.numberOfNeuronsByStep
                
                    Wnew{j} = rand(self.seed, self.numberOfInputNeurons, 1)*2-1;
                    Bnew{j} = rand(self.seed, 1, 1);

                    tempH = X*Wnew{j} + repmat(Bnew{j},size(X,1),1);
                    deltaH{j} = self.activationFunction(tempH);
                    clear tempH;

                    Dk1 = (self.H*self.pseudoInv);
                    Dk = (deltaH{j}'*(eye(size(Dk1)) - Dk1))/(deltaH{j}'*(eye(size(Dk1)) - Dk1)*deltaH{j});
                    
                    Uk = self.pseudoInv*(eye(size(Dk,2)) - deltaH{j}*Dk);
                    pseudoInvs{j} = [Uk; Dk];
                    outputWeight = pseudoInvs{j}*Y;

                    E(j) = norm([self.H, deltaH{j}]*outputWeight - Y,'fro');
                    
                end
                [~,idx] = min(E);
                E = E(idx);
                self.pseudoInv = pseudoInvs{idx};
                self.outputWeight = self.pseudoInv*Y;
                self.inputWeight = [self.inputWeight, Wnew{idx}];
                self.H = [self.H, deltaH{j}];
                self.biasOfHiddenNeurons = [self.biasOfHiddenNeurons, Bnew{idx}];
%                 disp(E)
                self.trainTime = toc - auxTime;
            end
            
        end
        
    end
end
