% RELM - Regularized Extreme Learning Machine Class
%   Train and Predict a SLFN based on Regularized Extreme Learning Machine
%   using the L2 norm of the matrix OutputWeight. Other norms will be available soon.
%
%   This code was implemented based on the following paper:
%
%   [1] Guang-Bin Huang, Hongming Zhou, Xiaojian Ding, and Rui Zhang, Extreme 
%       Learning Machine for Regression and Multiclass Classification. 
%       Trans. Sys. Man Cyber. Part B 42, 2 (April 2012), 513-529. 
%       http://dx.doi.org/10.1109/TSMCB.2011.2168604 
%       (http://ieeexplore.ieee.org/document/6035797/)
%
%   Attributes: 
%       Attributes between *.* must be informed.
%       R-ELM objects must be created using name-value pairs (see the Usage Example).
%
%         *NumberofInputNeurons*:   Number of neurons in the input layer.
%                Accepted Values:   Any positive integer.
%
%          NumberofHiddenNeurons:   Number of neurons in the hidden layer
%                Accepted Values:   Any positive integer (defaut = 1000).
%
%       Regularization_parameter:   Regularization Parameter (defaut = 1000)
%                Accepted Values:   Any positive real number.
%      
%             ActivationFunction:   Activation funcion for hidden layer   
%                Accepted Values:   Function handle (see [1]) or one of these strings:
%                                       'sig':     Sigmoid (default)
%                                       'sin':     Sine
%                                       'hardlim': Hard Limit
%                                       'tribas':  Triangular basis function
%                                       'radbas':  Radial basis function
%                           Seed:   Seed to generate the pseudo-random values.
%                                   This attribute is for reproducible research.
%                Accepted Values:   RandStream object or a integer seed for RandStream.
%
%       Attributes generated by the code:
%       
%                    InputWeight:   Weight matrix that connects the input 
%                                   layer to the hidden layer
%
%            BiasofHiddenNeurons:   Bias of hidden units
%
%                   OutputWeight:   Weight matrix that connects the hidden
%                                   layer to the output layer
%
%   Methods:
%
%       obj = RELM(varargin):        Creates RELM objects. varargin should be in
%                                    pairs. Look attributes
%
%       obj = obj.train(X,Y):        Method for training. X is the input of size N x n,
%                                    where N is (# of samples) and n is the (# of features).
%                                    Y is the output of size N x m, where m is (# of multiple outputs)
%                            
%       Yhat = obj.predict(X):       Predicts the output for X.
%
%   Usage Example:
%
%       load iris_dataset.mat
%       X    = irisInputs';
%       Y    = irisTargets';
%       relm  = RELM('NumberofInputNeurons', 4, 'NumberofHiddenNeurons',100);
%       relm  = relm.train(X, Y);
%       Yhat = relm.predict(X)

%   License:
%
%   Permission to use, copy, or modify this software and its documentation
%   for educational and research purposes only and without fee is here
%   granted, provided that this copyright notice and the original authors'
%   names appear on all copies and supporting documentation. This program
%   shall not be used, rewritten, or adapted as the basis of a commercial
%   software or hardware product without first obtaining permission of the
%   authors. The authors make no representations about the suitability of
%   this software for any purpose. It is provided "as is" without express
%   or implied warranty.
%
%       Federal University of Espirito Santo (UFES), Brazil
%       Computers and Neural Systems Lab. (LabCISNE)
%       Authors:    F. K. Inaba, B. L. S. Silva, D. L. Cosmo 
%       email:      labcisne@gmail.com
%       website:    github.com/labcisne/ELMToolbox
%       date:       Jan/2018

classdef RELM
    properties
        NumberofHiddenNeurons = 1000        
        Regularization_parameter = 1000
        ActivationFunction = 'sig'
        NumberofInputNeurons = []
        InputWeight = []
        BiasofHiddenNeurons = []
        OutputWeight = []
        Seed = []
    end
    methods
        function obj = RELM(varargin)
            for i = 1:2:nargin
                obj.(varargin{i}) = varargin{i+1};
            end
            if isnumeric(obj.Seed) && ~isempty(obj.Seed)
                obj.Seed = RandStream('mt19937ar','Seed', obj.Seed);
            elseif ~isa(obj.Seed, 'RandStream')
                obj.Seed = RandStream.getGlobalStream();
            end
            if isempty(obj.NumberofInputNeurons)
                throw(MException('EmptyNumberOfInputNeurons','Empty Number of Input Neurons'));
            end
            obj.InputWeight = rand(obj.Seed, obj.NumberofInputNeurons, obj.NumberofHiddenNeurons)*2-1;
            obj.BiasofHiddenNeurons = rand(obj.Seed, 1, obj.NumberofHiddenNeurons);
            
            if ~isa(obj.ActivationFunction,'function_handle') && ischar(obj.ActivationFunction)
                switch lower(obj.ActivationFunction)
                    case {'sig','sigmoid'}
                        %%%%%%%% Sigmoid
                        obj.ActivationFunction = @(tempH) 1 ./ (1 + exp(-tempH));
                    case {'sin','sine'}
                        %%%%%%%% Sine
                        obj.ActivationFunction = @(tempH) sin(tempH);
                    case {'hardlim'}
                        %%%%%%%% Hard Limit
                        obj.ActivationFunction = @(tempH) double(hardlim(tempH));
                    case {'tribas'}
                        %%%%%%%% Triangular basis function
                        obj.ActivationFunction = @(tempH) tribas(tempH);
                    case {'radbas'}
                        %%%%%%%% Radial basis function
                        obj.ActivationFunction = @(tempH) radbas(tempH);
                        %%%%%%%% More activation functions can be added here
                end
            else
                throw(MException('ActivationFunctionError','Error Activation Function'));
            end
        end
        function self = train(self, X, Y)            
            tempH = X*self.InputWeight + repmat(self.BiasofHiddenNeurons,size(X,1),1);
            clear X;
            H = self.ActivationFunction(tempH);
            if size(H,1)>=size(H,2)
                self.OutputWeight = (eye(size(H,2))/self.Regularization_parameter + H' * H) \ H' * Y;
            else
                self.OutputWeight = H' * ((eye(size(H,1))/self.Regularization_parameter + H * H') \ Y);
            end
        end
        function Yhat = predict(self, X)
            tempH = X*self.InputWeight + repmat(self.BiasofHiddenNeurons,size(X,1),1);
            clear X;
            H = self.ActivationFunction(tempH);
            Yhat = H * self.OutputWeight;
        end
    end
end
